nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_headers: ['X-Custom-Auth']
    allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
    max_age: 3600
  paths:
    '^/':
      allow_origin: ['*']
      allow_headers: ['Content-Type']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
      max_age: 3600
